// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Persistence;

#nullable disable

namespace Persistence.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.14");

            modelBuilder.Entity("Domain.ProjectFeatureFlag", b =>
                {
                    b.Property<int>("ProjectFeatureFlagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("TEXT");

                    b.Property<string>("FlagName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsApiChanged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsFredChanged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsIvanChanged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsOtherChanged")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsUiChanged")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OtherChangedApps")
                        .HasColumnType("TEXT");

                    b.Property<string>("PRLinks")
                        .HasColumnType("TEXT");

                    b.Property<string>("TaskNumber")
                        .HasColumnType("TEXT");

                    b.Property<string>("WorkedOnBy")
                        .HasColumnType("TEXT");

                    b.HasKey("ProjectFeatureFlagId");

                    b.ToTable("ProjectFeatureFlags");
                });
#pragma warning restore 612, 618
        }
    }
}
